<?php

namespace ContainerMwIgxVH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__AnznsPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..AnznsP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\CategoryController::new' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\CategoryController::new()', 'getCategoryControllernewService', true],
            'App\\Controller\\CategoryController::showAll' => ['privates', '.service_locator.JuymgO0.App\\Controller\\CategoryController::showAll()', 'getCategoryControllershowAllService', true],
            'App\\Controller\\DirectorController::new' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\DirectorController::new()', 'getDirectorControllernewService', true],
            'App\\Controller\\DirectorController::showAll' => ['privates', '.service_locator.XS9BzWN.App\\Controller\\DirectorController::showAll()', 'getDirectorControllershowAllService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\CategoryController:new' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\CategoryController::new()', 'getCategoryControllernewService', true],
            'App\\Controller\\CategoryController:showAll' => ['privates', '.service_locator.JuymgO0.App\\Controller\\CategoryController::showAll()', 'getCategoryControllershowAllService', true],
            'App\\Controller\\DirectorController:new' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\DirectorController::new()', 'getDirectorControllernewService', true],
            'App\\Controller\\DirectorController:showAll' => ['privates', '.service_locator.XS9BzWN.App\\Controller\\DirectorController::showAll()', 'getDirectorControllershowAllService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CategoryController::new' => '?',
            'App\\Controller\\CategoryController::showAll' => '?',
            'App\\Controller\\DirectorController::new' => '?',
            'App\\Controller\\DirectorController::showAll' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CategoryController:new' => '?',
            'App\\Controller\\CategoryController:showAll' => '?',
            'App\\Controller\\DirectorController:new' => '?',
            'App\\Controller\\DirectorController:showAll' => '?',
        ]);

        if (isset($container->privates['.service_locator..AnznsP'])) {
            return $container->privates['.service_locator..AnznsP'];
        }

        return $container->privates['.service_locator..AnznsP'] = $instance;
    }
}
