<?php

namespace ContainerMwIgxVH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDirectorControllershowAllService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XS9BzWN.App\Controller\DirectorController::showAll()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XS9BzWN.App\\Controller\\DirectorController::showAll()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'directorRepository' => ['privates', 'App\\Repository\\DirectorRepository', 'getDirectorRepositoryService', true],
        ], [
            'directorRepository' => 'App\\Repository\\DirectorRepository',
        ]))->withContext('App\\Controller\\DirectorController::showAll()', $container);
    }
}
